services:
  filebrowser:
    container_name: filebrowser
    hostname: filebrowser
    image: hurlenko/filebrowser:latest
    user: 1000:1000
    volumes:
      - /:/data
      - ./config:/config
      - ./branding:/branding
    networks:
      - nginx_default
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=filebrowser.isame-lab.com
      - LETSENCRYPT_HOST=filebrowser.isame-lab.com
      - VIRTUAL_PORT=8080
      - TZ=America/New_York

networks:
  nginx_default:
    external: true