version: "3.3"
services:
  filebrowser:
    container_name: filebrowser
    hostname: filebrowser
    image: "hurlenko/filebrowser"
    user: 1000:1000
    volumes:
      - "/:/data"
      - "~/filebrowser:/config"
    networks:
      - nginx_default
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=filebrowser.isame-lab.com
      - LETSENCRYPT_HOST=filebrowser.isame-lab.com
      - VIRTUAL_PORT=8080
      - TZ=America/New_York
networks:
  nginx_default:
    external: true
