version: '3.3'
services:
    filebrowser:
        container_name: filebrowserTest
        hostname: filebrowser
        user: '1000:1000'
        volumes:
            - '/:/srv:rw'
            - '/home/isame/filebrowser/filebrowser.db:/database.db:rw'
            - /database.db
        # network_mode: filebrowser_default
        networks:
            - nginx_default
        ports:
            - '8070:80'
        expose: 
            - '8070'
        
        restart: unless-stopped
        image: 'filebrowser/filebrowser:latest'
        environment:
            - VIRTUAL_HOST=filebrowser.isame-lab.com
            - VIRTUAL_PORT=8070

networks:
  nginx_default:
    external: true