services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VIRTUAL_HOST=jellyfin.isame-lab.com
      - VIRTUAL_PORT=8096
      - LETSENCRYPT_HOST=jellyfin.isame-lab.com
    volumes:
      - /home/isame/labRebuild/containers/jellyfin/config:/config
      - /kasm_shared/tvshows:/data/tvshows
      - /kasm_shared/movies:/data/movies
      - /kasm_shared/music:/data/music
    networks:
      - nginx_default
    restart: unless-stopped
    image: docker.io/linuxserver/jellyfin:latest

networks:
  nginx_default:
    external: true