services:
  nginx:
    container_name: nginx-web
    hostname: nginx-web
    image: nginx
    volumes:
      - /site:/usr/share/nginx/html/
    environment:
      - VIRTUAL_HOST=isame-lab.com
      - LETSENCRYPT_HOST=isame-lab.com
      - NGINX_HOST=isame-lab.com
  vsftpd:
    container_name: vsftpd
    hostname: vsftpd
    env_file:
      - ftp_pass.env
    volumes:
      - /site:/home/vsftpd
      - ./logs/vsftpd:/var/log/vsftpd
    privileged: true
    ports:
      - 20:20
      - 21:21
    restart: unless-stopped
    image: fauria/vsftpd
  copybot:
    container_name: copybot
    hostname: copybot
    environment:
      - NODE_VERSION=18.8.0
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: docker.io/isame/copybot:development
networks:
  default:
    external: true
    name: nginx_default
