services:
  veloren-server:
    image: registry.gitlab.com/veloren/veloren/server-cli:weekly
    stdin_open: true
    tty: true
    container_name: veloren-server
    restart: on-failure:0
    volumes:
        - ./userdata:/opt/userdata
    environment:
        - RUST_LOG=debug,common::net=info
        - VIRTUAL_HOST=veloren.isame-lab.com
        - VIRTUAL_PORT=14004
    ports:
      - 14004:14004
    networks:
      - nginx_default
networks:
  nginx_default:
    external: true