services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    hostname: pwndrop
    environment:
      - SECRET_PATH=/downloads
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=pwndrop.isame-lab.com
      - LETSENCRYPT_HOST=pwndrop.isame-lab.com
    networks:
      - nginx_default
    volumes:
      - pwndrop_data:/config
    # ports:
    #   - 6969:8080
    restart: unless-stopped
volumes:
  pwndrop_data:
    external: true
networks:
  nginx_default:
    external: true
