version: '3.3'
services:
    linuxserver:
        image: 'lscr.io/linuxserver/pwndrop:latest'
        container_name: pwndropTest
        hostname: pwndrop
        environment:
            - SECRET_PATH=/downloads
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
            - VIRTUAL_HOST=pwndrop.isame-lab.com
            - LETSENCRYPT_HOST=pwndrop.isame-lab.com
            - VIRTUAL_PORT=8080
        volumes:
            - './data:/config'
        networks:
            - nginx_default

        ports:
            - '8080'
        restart: unless-stopped
networks:
  nginx_default:
    external: true