version: '3'

services:
  app:
    image: 'nginx'
    restart: unless-stpped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    
