services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    hostname: nginx
    environment:
      - DEFAULT_HOST=isame-lab.com
      - VIRTUAL_HOST=DEFAULT_HOST
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
    environment:
      - DEFAULT_EMAIL=sgriffith0891@gmail.com
    networks:
      - nginx_default
    restart: unless-stopped
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  nginx_default:
    external: true