version: '3.3'
services:
    nginx-proxy:
      container_name: nginx
      ports:
          - '80:80'
      volumes:
          - '/var/run/docker.sock:/tmp/docker.sock:ro'
          - './vhost.d:/etc/nginx/vhost.d:ro'
          # - './nginx.conf:/etc/nginx/nginx.conf'
          # - './conf:/etc/nginx'
      image: nginxproxy/nginx-proxy
